version: '3.8'
services:
  fe_admin:
    build:
      context: ./coupon_redemption_admin_fe
    ports:
      - "8080:8000"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:3123
    depends_on:
      - server

  fe_public:
    build:
      context: ./coupon_redemption_fe
    ports:
      - "8081:8001"
    environment:
      - VITE_REACT_APP_API_URL=http://localhost:3123
    depends_on:
      - server

  server:
    build:
      context: ./coupon_redemption_be
    ports:
      - "3123:3000"
    environment:
      - DATABASE_URL=postgresql://root:root@db:5432/coupon_redemption
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: coupon_redemption
      TZ: Asia/Shanghai
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
